In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
movies=pd.read_csv('src/data/movies.csv')
credits=pd.read_csv('src/data/credits.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movies.shape

(4803, 20)

In [6]:
credits.shape

(4803, 4)

In [7]:
movies=movies.merge(credits, on='title')

In [8]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [9]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [10]:
movies=movies[['movie_id','title','genres','overview','release_date','keywords','cast','crew',]]

In [11]:
movies.head()

,movie_id,title,genres,overview,release_date,keywords,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...",2009-12-10,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha...",2007-05-19,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bond’s past sends him o...,2015-10-26,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...,2012-07-16,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","John Carter is a war-weary, former military ca...",2012-03-07,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [12]:
movies.isnull().sum()

movie_id        0
title           0
genres          0
overview        3
release_date    1
keywords        0
cast            0
crew            0
dtype: int64

In [13]:
movies[movies['overview'].isnull()]['title']

2658    Chiamatemi Francesco - Il Papa della gente
4145                   To Be Frank, Sinatra at 100
4437                                   Food Chains
Name: title, dtype: object

In [14]:
movies.dropna(inplace=True)

In [15]:
movies.shape

(4805, 8)

In [16]:
movies.duplicated().sum()

np.int64(0)

In [17]:
movies.iloc[0]['genres']

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [18]:
type(movies.iloc[0]['genres'])

str

In [19]:
import ast

def convert(text):
    l=[]
    for i in ast.literal_eval(text):
        l.append(i['name'])

    return l

In [20]:
movies['genres']=movies['genres'].apply(convert)

In [21]:
movies.head()

,movie_id,title,genres,overview,release_date,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...",2009-12-10,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...",2007-05-19,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,2015-10-26,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,2012-07-16,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...",2012-03-07,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [22]:
movies.iloc[0]['keywords']

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [23]:
movies['keywords']=movies['keywords'].apply(convert)

In [24]:
movies['keywords']

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4805, dtype: object

In [25]:
movies['keywords'].isnull().sum()

np.int64(0)

In [26]:
movies.iloc[0]['cast']

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [27]:
import ast

def convert_cast(text):
    l=[]
    counter=0
    for i in ast.literal_eval(text):
        if counter<3:
            l.append(i['name'])
        counter+=1

    return l

In [28]:
movies['cast']=movies['cast'].apply(convert_cast)
movies.head()

,movie_id,title,genres,overview,release_date,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...",2009-12-10,"[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...",2007-05-19,"[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,2015-10-26,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,2012-07-16,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...",2012-03-07,"[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [29]:
movies.iloc[0]['crew']

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [30]:
import ast

def fetch_dir(text):
    l=[]
    for i in ast.literal_eval(text):
        if i['job']=='Director':
            l.append(i['name'])
            break

    return l

In [31]:
movies['crew']=movies['crew'].apply(fetch_dir)

In [32]:
movies.head()

,movie_id,title,genres,overview,release_date,keywords,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...",2009-12-10,"[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...",2007-05-19,"[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,2015-10-26,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,2012-07-16,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...",2012-03-07,"[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [33]:
type(movies.iloc[0]['release_date'])

str

In [34]:
def release_year(date):
    return date[:4]

In [35]:
movies['release_year']=movies['release_date'].apply(release_year)

In [36]:
movies.drop('release_date',axis=1,inplace=True)
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew,release_year
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],2009
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],2007
2,206647,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],2015
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],2012
4,49529,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],2012

In [37]:
movies.iloc[0]['overview']

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [38]:
movies['overview']

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: overview, Length: 4805, dtype: object

In [39]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [40]:
movies['overview'].head()

0    [In, the, 22nd, century,, a, paraplegic, Marin...
1    [Captain, Barbossa,, long, believed, to, be, d...
2    [A, cryptic, message, from, Bond’s, past, send...
3    [Following, the, death, of, District, Attorney...
4    [John, Carter, is, a, war-weary,, former, mili...
Name: overview, dtype: object

In [41]:
movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4805, dtype: object

In [42]:
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])
movies['overview']=movies['overview'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

In [43]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew,release_year
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],2009
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],2007
2,206647,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],2015
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],2012
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],2012

In [44]:
movies['tags']=movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [45]:
movies.head()

,movie_id,title,genres,overview,keywords,cast,crew,release_year,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],2009,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],2007,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],2015,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],2012,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],2012,"[John, Carter, is, a, war-weary,, former, mili..."

In [46]:
new_df = movies[['movie_id','title','tags']]

In [47]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\PIYUSH\AppData\Local\Temp\ipykernel_15124\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [48]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [49]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science Fiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [50]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\PIYUSH\AppData\Local\Temp\ipykernel_15124\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [51]:
new_df.tags[0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy science fiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [52]:
new_df.tags[1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp orlandobloom keiraknightley goreverbinski"

In [53]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [54]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [55]:
vectors[1]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [56]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [57]:
features = cv.get_feature_names_out()
print(list(features))

['000', '007', '10', '100', '11', '12', '13', '14', '15', '16', '17', '17th', '18', '18th', '18thcentury', '19', '1930s', '1940s', '1950s', '1960s', '1970s', '1980', '1980s', '1985', '1990s', '19th', '19thcentury', '20', '200', '2009', '20th', '24', '25', '30', '300', '3d', '40', '50', '500', '60', '60s', '70', 'aaron', 'aaroneckhart', 'abandoned', 'abducted', 'abigailbreslin', 'abilities', 'ability', 'able', 'aboard', 'abuse', 'abusive', 'academy', 'accept', 'accepted', 'accepts', 'access', 'accident', 'accidental', 'accidentally', 'accompanied', 'accomplish', 'account', 'accountant', 'accused', 'ace', 'achieve', 'act', 'acting', 'action', 'actionhero', 'actions', 'activist', 'activities', 'activity', 'actor', 'actors', 'actress', 'acts', 'actual', 'actually', 'adam', 'adams', 'adamsandler', 'adamshankman', 'adaptation', 'adapted', 'addict', 'addicted', 'addiction', 'adolescence', 'adopt', 'adopted', 'adoption', 'adopts', 'adrienbrody', 'adult', 'adultery', 'adulthood', 'adults', 'advantage', 'adventure', 'adventures', 'advertising', 'advice', 'affair', 'affairs', 'affection', 'affections', 'afghanistan', 'africa', 'african', 'africanamerican', 'aftercreditsstinger', 'afterlife', 'aftermath', 'age', 'aged', 'agedifference', 'agency', 'agenda', 'agent', 'agents', 'aggressive', 'aging', 'ago', 'agree', 'agrees', 'ahead', 'aid', 'aided', 'aids', 'ailing', 'air', 'airplane', 'airplanecrash', 'airport', 'aka', 'al', 'alabama', 'alan', 'alaska', 'albert', 'alcatraz', 'alcohol', 'alcoholic', 'alcoholism', 'alecbaldwin', 'alex', 'alexkendrick', 'alfredhitchcock', 'alfredmolina', 'ali', 'alice', 'alien', 'alieninvasion', 'alienlife', 'alienplanet', 'aliens', 'alike', 'alive', 'allen', 'alliance', 'allied', 'allies', 'allow', 'allowing', 'allows', 'ally', 'alongside', 'alpacino', 'alpha', 'alter', 'alternate', 'alternative', 'alyssa', 'alzheimer', 'amanda', 'amandapeet', 'amandaseyfried', 'amateur', 'amazing', 'amazon', 'ambassador', 'ambition', 'ambitious', 'ambulance', 'ambush', 'america', 'american', 'americanabroad', 'americancivilwar', 'americanfootball', 'americanfootballplayer', 'americans', 'amid', 'amidst', 'amnesia', 'amp', 'amsterdam', 'amusement', 'amusementpark', 'amy', 'amyadams', 'amysmart', 'ana', 'anakin', 'analyst', 'anarchiccomedy', 'ancient', 'ancientrome', 'ancientworld', 'anderson', 'andiemacdowell', 'andrew', 'android', 'andy', 'andygarcía', 'angel', 'angela', 'angelabassett', 'angeles', 'angelinajolie', 'angels', 'anger', 'anglee', 'angry', 'animal', 'animalattack', 'animalhorror', 'animals', 'animated', 'animation', 'anime', 'anjelicahuston', 'ann', 'anna', 'annabelle', 'annafaris', 'annakendrick', 'anne', 'annehathaway', 'annemoss', 'annettebening', 'annie', 'anniversary', 'announces', 'annual', 'anonymity', 'answer', 'answers', 'ant', 'antarctic', 'anthology', 'anthony', 'anthonyanderson', 'anthonyhopkins', 'anthonymackie', 'anthropomorphism', 'anti', 'antics', 'antihero', 'antoinefuqua', 'antoniobanderas', 'antonyelchin', 'apart', 'apartheid', 'apartment', 'ape', 'apes', 'apocalypse', 'apocalyptic', 'apparent', 'apparently', 'appear', 'appears', 'apple', 'appointed', 'apprentice', 'approach', 'approaches', 'approaching', 'april', 'aquarium', 'arab', 'arch', 'archaeologist', 'archeology', 'archer', 'architect', 'arctic', 'area', 'aren', 'arena', 'argument', 'arise', 'aristocrat', 'armed', 'arms', 'army', 'arnold', 'arnoldschwarzenegger', 'arrangedmarriage', 'arrest', 'arrested', 'arrival', 'arrive', 'arrives', 'arriving', 'arrogant', 'art', 'arthur', 'artificialintelligence', 'artist', 'artistic', 'artists', 'arts', 'ashley', 'ashleyjudd', 'ashtonkutcher', 'asia', 'aside', 'ask', 'asked', 'asking', 'asks', 'aspirations', 'aspiring', 'assassin', 'assassinate', 'assassination', 'assassins', 'assault', 'assigned', 'assignment', 'assistant', 'assumes', 'asteroid', 'astronaut', 'astronauts', 'asylum', 'athlete', 'atomicbomb', 'attack', 'attacked', 'attacks', 'attempt', 'attempting', 'attempts', 'attending', 'attends', 'attention', 'attitude', 'attorney', 'attracted', 'attraction', 'attractive', 'audience', 'audiences', 'audition', 'august', 'aunt', 'austin', 'australia', 'australian', 'author', 'authorities', 'authority', 'autism', 'auto', 'avenge', 'average', 'avoid', 'awaits', 'awakens', 'award', 'away', 'awry', 'ax', 'babe', 'baby', 'bachelor', 'backdrop', 'background', 'backgrounds', 'bad', 'bag', 'bahamas', 'bail', 'balance', 'ball', 'ballet', 'baltimore', 'band', 'bandits', 'bangkok', 'banished', 'bank', 'banker', 'bankrobber', 'bankrobbery', 'bar', 'barely', 'bargained', 'barn', 'barney', 'barry', 'barrylevinson', 'bars', 'base', 'baseball', 'based', 'basedoncomicbook', 'basedongraphicnovel', 'basedonnovel', 'basedonplay', 'basedonstagemusical', 'basedontrueevents', 'basedontruestory', 'basedontvseries', 'basedonvideogame', 'basedonyoungadultnovel', 'basement', 'basketball', 'batman', 'battle', 'battlefield', 'battles', 'battling', 'bay', 'beach', 'bear', 'bears', 'beast', 'beasts', 'beat', 'beating', 'beautiful', 'beautifulwoman', 'beauty', 'becky', 'becominganadult', 'bed', 'bedroom', 'beer', 'befriends', 'began', 'begin', 'beginning', 'begins', 'behavior', 'beings', 'beliefs', 'believe', 'believed', 'believes', 'believing', 'beloved', 'ben', 'benaffleck', 'beneath', 'benfoster', 'beniciodeltoro', 'benjamin', 'benjaminbratt', 'benkingsley', 'bennett', 'benstiller', 'bent', 'berlin', 'best', 'bestfriend', 'bet', 'beth', 'betrayal', 'betrayed', 'bettemidler', 'better', 'betty', 'beverly', 'bible', 'big', 'bigger', 'biggest', 'biker', 'bikini', 'billhader', 'billionaire', 'billmurray', 'billnighy', 'billpaxton', 'billpullman', 'billy', 'billybobthornton', 'billycrudup', 'billycrystal', 'biography', 'bird', 'birth', 'birthday', 'bisexual', 'bishop', 'bit', 'bite', 'bitter', 'bizarre', 'black', 'blackmagic', 'blackmail', 'blackpeople', 'blade', 'blame', 'blind', 'bliss', 'block', 'blonde', 'blood', 'bloodsplatter', 'bloodthirsty', 'bloody', 'blow', 'blue', 'board', 'boarding', 'boardingschool', 'boat', 'bob', 'bobby', 'bobbyfarrelly', 'bobhoskins', 'bodies', 'body', 'bodyguard', 'bold', 'bollywood', 'bomb', 'bombing', 'bond', 'bonds', 'bone', 'book', 'books', 'border', 'bored', 'boredom', 'boring', 'born', 'boss', 'boston', 'botched', 'bound', 'boundaries', 'bounty', 'bountyhunter', 'box', 'boxer', 'boxing', 'boy', 'boyfriend', 'boys', 'bradleycooper', 'bradpitt', 'brain', 'brand', 'brave', 'bravery', 'brazil', 'brazilian', 'break', 'breakdown', 'breaking', 'breaks', 'brendanfraser', 'brendangleeson', 'brent', 'brettratner', 'brian', 'briandepalma', 'bride', 'bridge', 'brief', 'brien', 'bright', 'brilliant', 'bring', 'bringing', 'brings', 'brink', 'britain', 'british', 'britishsecretservice', 'brittanymurphy', 'broadway', 'broke', 'broken', 'broker', 'brooklyn', 'brooks', 'brothel', 'brother', 'brotherbrotherrelationship', 'brothers', 'brothersisterrelationship', 'brought', 'brown', 'bruce', 'brucewillis', 'brutal', 'brutality', 'brutally', 'bryansinger', 'buck', 'buddies', 'buddy', 'buddycomedy', 'budget', 'build', 'building', 'builds', 'built', 'bully', 'bullying', 'bumbling', 'bunch', 'bunker', 'bunny', 'burglar', 'buried', 'burned', 'burns', 'bus', 'bush', 'business', 'businessman', 'bust', 'busy', 'butcher', 'butler', 'butt', 'buy', 'buzz', 'cabin', 'caesar', 'cage', 'cairo', 'cal', 'california', 'called', 'calling', 'calls', 'calvin', 'camcorder', 'came', 'camera', 'cameraman', 'cameras', 'camerondiaz', 'camp', 'campaign', 'campbell', 'camping', 'campus', 'canada', 'canadian', 'cancer', 'candidate', 'candy', 'canine', 'cannibal', 'canuxploitation', 'capable', 'caper', 'capital', 'capitalism', 'capt', 'captain', 'captive', 'capture', 'captured', 'captures', 'car', 'caraccident', 'carchase', 'carcrash', 'card', 'care', 'career', 'carefree', 'cares', 'caretaker', 'careymulligan', 'caribbean', 'carjourney', 'carl', 'carlagugino', 'carmen', 'carnival', 'carol', 'carolina', 'carrace', 'carrie', 'carry', 'carrying', 'cars', 'cartel', 'carter', 'cartoon', 'caryelwes', 'case', 'caseyaffleck', 'cash', 'casino', 'cast', 'castle', 'cat', 'cataclysm', 'catastrophe', 'catch', 'catches', 'cateblanchett', 'catherinekeener', 'catherinezeta', 'catholic', 'catholicism', 'cattle', 'caught', 'cause', 'caused', 'causes', 'causing', 'cavalry', 'cave', 'celebrate', 'celebrated', 'celebration', 'celebrity', 'cellphone', 'cemetery', 'center', 'centered', 'centers', 'central', 'centuries', 'century', 'ceremony', 'certain', 'chain', 'chainsaw', 'challenge', 'challenged', 'challenges', 'champion', 'championship', 'chance', 'change', 'changed', 'changes', 'changing', 'channingtatum', 'chaos', 'chaotic', 'chapter', 'character', 'characters', 'charge', 'charged', 'charismatic', 'charles', 'charlie', 'charliesheen', 'charlizetheron', 'charlotte', 'charm', 'charming', 'chase', 'chased', 'chauffeur', 'cheating', 'cheerleader', 'chef', 'chemical', 'cher', 'chicago', 'chicken', 'chief', 'child', 'childabuse', 'childhero', 'childhood', 'childprodigy', 'children', 'chilling', 'china', 'chinese', 'chip', 'chiwetelejiofor', 'chloe', 'chloëgracemoretz', 'chloësevigny', 'chocolate', 'choice', 'choices', 'choose', 'chosen', 'chowyun', 'chris', 'chriscolumbus', 'chriscooper', 'chrisevans', 'chrishemsworth', 'chrisklein', 'chrispine', 'chrisrock', 'christ', 'christian', 'christianbale', 'christianity', 'christianslater', 'christinaapplegate', 'christinaricci', 'christine', 'christmas', 'christmasparty', 'christmastree', 'christopher', 'christopherlambert', 'christopherlloyd', 'christophernolan', 'christopherplummer', 'christopherwalken', 'christophwaltz', 'chronicle', 'chronicles', 'chuck', 'church', 'cia', 'cigarettesmoking', 'cillianmurphy', 'cinema', 'circle', 'circuit', 'circumstances', 'circus', 'cities', 'citizens', 'city', 'civil', 'civilization', 'civilwar', 'claim', 'claims', 'claire', 'clairedanes', 'clan', 'clark', 'clash', 'class', 'classes', 'classic', 'classmate', 'classmates', 'classroom', 'claudevandamme', 'clay', 'clean', 'clear', 'clerk', 'client', 'clients', 'climate', 'climbing', 'clinteastwood', 'cliveowen', 'clock', 'clone', 'cloning', 'close', 'closer', 'club', 'clubs', 'clues', 'clutches', 'coach', 'coast', 'cocaine', 'cocky', 'code', 'cody', 'coffin', 'cohen', 'col', 'cold', 'coldwar', 'cole', 'colin', 'colinfarrell', 'colinfirth', 'collapse', 'colleague', 'colleagues', 'collect', 'collection', 'collector', 'college', 'collide', 'collision', 'colonel', 'colony', 'color', 'colorado', 'colorful', 'coma', 'combat', 'combined', 'come', 'comeback', 'comedian', 'comedic', 'comedy', 'comes', 'comet', 'comfort', 'comic', 'comics', 'coming', 'comingofage', 'comingout', 'command', 'commander', 'commercial', 'commit', 'commitment', 'committed', 'common', 'communication', 'community', 'companion', 'company', 'compete', 'competing', 'competition', 'complete', 'completely', 'complex', 'complicated', 'complications', 'composer', 'computer', 'computervirus', 'conan', 'concert', 'conclusion', 'condition', 'confession', 'confidence', 'confident', 'conflict', 'confront', 'confronted', 'confused', 'congress', 'conman', 'connected', 'connection', 'connell', 'connor', 'conquer', 'conscience', 'consequences', 'conservative', 'considered', 'conspiracy', 'constant', 'constantly', 'construction', 'contact', 'contain', 'contemporary', 'contend', 'contest', 'continue', 'continues', 'continuing', 'contract', 'control', 'controlled', 'controlling', 'controversial', 'convention', 'converge', 'convict', 'convicted', 'convince', 'convinced', 'convinces', 'cook', 'cooking', 'cool', 'cooper', 'cop', 'cope', 'cops', 'core', 'corner', 'corners', 'corporate', 'corporation', 'corpse', 'corrupt', 'corruption', 'cost', 'costume', 'couldn', 'count', 'countess', 'countless', 'countries', 'country', 'countryhouse', 'countrymusic', 'countryside', 'county', 'coup', 'couple', 'couples', 'courage', 'courageous', 'course', 'court', 'courtcase', 'courteneycox', 'courtroom', 'cousin', 'cover', 'covert', 'cow', 'cowardliness', 'cowboy', 'crab', 'crack', 'craft', 'craig', 'crane', 'crash', 'crashes', 'crashing', 'crazy', 'create', 'created', 'creates', 'creation', 'creator', 'creature', 'creatures', 'credit', 'creepy', 'crew', 'crime', 'crimefighter', 'crimes', 'criminal', 'criminals', 'crisis', 'critical', 'crocodile', 'crook', 'crooked', 'cross', 'crossed', 'crosses', 'crown', 'cruel', 'cruelty', 'cruise', 'crush', 'crystal', 'cuba', 'cubagoodingjr', 'cult', 'cultfilm', 'cultural', 'culture', 'cultureclash', 'cunning', 'cup', 'cure', 'curious', 'current', 'curse', 'cursed', 'custody', 'customers', 'cut', 'cyberpunk', 'cyborg', 'dad', 'daily', 'dakotafanning', 'damage', 'dan', 'danaykroyd', 'dance', 'dancer', 'dancing', 'danger', 'dangerous', 'dangers', 'daniel', 'danielcraig', 'danielday', 'danielradcliffe', 'danny', 'dannyboyle', 'dannydevito', 'dannyglover', 'darcy', 'dare', 'daring', 'dark', 'darkcomedy', 'darkest', 'darkness', 'darylhannah', 'dashing', 'date', 'dates', 'dating', 'daughter', 'daughters', 'dave', 'david', 'davidarquette', 'davidcronenberg', 'davidduchovny', 'davidfincher', 'davidgordongreen', 'davidmorse', 'davido', 'davidschwimmer', 'davis', 'daxshepard', 'day', 'days', 'dc', 'dccomics', 'dea', 'dead', 'deadly', 'deaf', 'deal', 'dealer', 'dealers', 'dealing', 'deals', 'dean', 'death', 'deathofafriend', 'deathpenalty', 'deaths', 'debt', 'debut', 'decade', 'decades', 'decapitation', 'deceased', 'deceit', 'deception', 'decide', 'decided', 'decides', 'decision', 'decisions', 'dedicated', 'deeds', 'deep', 'deeper', 'deeply', 'defeat', 'defend', 'defense', 'deliver', 'delivers', 'delusion', 'demanding', 'demands', 'demimoore', 'demon', 'demonic', 'demonicpossession', 'demons', 'dennisdugan', 'dennishopper', 'dennisquaid', 'dentist', 'denzelwashington', 'department', 'depressed', 'depression', 'deputy', 'deranged', 'derek', 'descend', 'desert', 'deserted', 'designed', 'desire', 'desires', 'desolate', 'despair', 'desperate', 'desperately', 'desperation', 'despite', 'destined', 'destiny', 'destroy', 'destroyed', 'destroying', 'destruction', 'destructive', 'details', 'detective', 'detectives', 'detention', 'determination', 'determine', 'determined', 'detroit', 'devastating', 'develop', 'developed', 'developer', 'developing', 'develops', 'device', 'devil', 'devious', 'devoted', 'diabolical', 'diagnosed', 'dialogue', 'diamond', 'diane', 'dianekeaton', 'dianekruger', 'dianelane', 'diary', 'dick', 'dictator', 'did', 'didn', 'die', 'died', 'diego', 'dies', 'differences', 'different', 'difficult', 'digging', 'dignity', 'diner', 'dinner', 'dinosaur', 'dinosaurs', 'dire', 'directed', 'direction', 'director', 'dirt', 'dirty', 'dirtycop', 'disabled', 'disappearance', 'disappeared', 'disappears', 'disaster', 'disastrous', 'discover', 'discovered', 'discovering', 'discovers', 'discovery', 'disease', 'disfigurement', 'disgraced', 'disguise', 'dishonesty', 'disillusioned', 'disney', 'disorder', 'dispatched', 'distant', 'district', 'distrust', 'disturbed', 'disturbing', 'diva', 'divided', 'division', 'divorce', 'divorced', 'dna', 'doc', 'doctor', 'document', 'documentary', 'documents', 'does', 'doesn', 'dog', 'dogs', 'doing', 'doll', 'dollar', 'dollars', 'dolphin', 'dolphlundgren', 'domination', 'don', 'donaldpetrie', 'donaldsutherland', 'doncheadle', 'donnell', 'doomed', 'doomsday', 'door', 'doorstep', 'doppelganger', 'dorothy', 'double', 'doublelife', 'doubt', 'doubts', 'doug', 'douglas', 'dougliman', 'dr', 'dracula', 'drag', 'dragon', 'drama', 'dramatic', 'draw', 'drawing', 'drawn', 'draws', 'dream', 'dreams', 'drew', 'drewbarrymore', 'drifter', 'drink', 'drinking', 'drive', 'driven', 'driver', 'drives', 'driving', 'drop', 'drowning', 'drug', 'drugabuse', 'drugaddiction', 'drugdealer', 'druglord', 'drugs', 'drugtraffic', 'drunk', 'drunken', 'du', 'dualidentity', 'dude', 'duel', 'duke', 'dumped', 'duo', 'duringcreditsstinger', 'dustinhoffman', 'dutch', 'duty', 'dwarves', 'dwaynejohnson', 'dying', 'dyinganddeath', 'dylan', 'dynamic', 'dynasty', 'dysfunctional', 'dysfunctionalfamily', 'dystopia', 'dystopicfuture', 'eager', 'earlier', 'early', 'earn', 'earth', 'earthquake', 'east', 'easy', 'eating', 'eccentric', 'economic', 'economy', 'eddie', 'eddiegriffin', 'eddiemurphy', 'edge', 'edharris', 'editor', 'education', 'edward', 'edwardburns', 'edwardnorton', 'effort', 'efforts', 'egg', 'ego', 'egypt', 'egyptian', 'el', 'elaborate', 'elderly', 'election', 'elements', 'eliaskoteas', 'elijahwood', 'eliminate', 'elisabethshue', 'elite', 'elizabeth', 'elizabethbanks', 'ella', 'ellenburstyn', 'ellenpage', 'ellie', 'elliot', 'ellis', 'elusive', 'elves', 'elvis', 'embark', 'embarking', 'embarks', 'embassy', 'embroiled', 'emerge', 'emergency', 'emerges', 'emilehirsch', 'emily', 'emilyblunt', 'emilymortimer', 'emilywatson', 'emma', 'emmastone', 'emmathompson', 'emmawatson', 'emotional', 'emotionally', 'emotions', 'emperor', 'empire', 'employee', 'employees', 'employer', 'employs', 'encounter', 'encounters', 'end', 'ended', 'ending', 'endless', 'endoftheworld', 'ends', 'enemies', 'enemy', 'energy', 'enforcement', 'engaged', 'engagement', 'engineer', 'england', 'english', 'enigmatic', 'enjoy', 'enlist', 'enlists', 'enormous', 'ensemblecast', 'ensues', 'entangled', 'enter', 'enterprise', 'enters', 'entertainer', 'entertaining', 'entire', 'entirely', 'entity', 'environment', 'environmental', 'epic', 'epidemic', 'era', 'eric', 'ericbana', 'erin', 'ernest', 'eroticism', 'erupts', 'escapade', 'escape', 'escaped', 'escapes', 'escaping', 'escort', 'especially', 'espionage', 'establishment', 'estate', 'estranged', 'eternal', 'ethan', 'ethanhawke', 'europe', 'european', 'eva', 'evacuation', 'evamendes', 'evanrachelwood', 'eve', 'evening', 'event', 'events', 'eventually', 'everybody', 'everyday', 'evidence', 'evil', 'evolution', 'ewanmcgregor', 'ex', 'exact', 'exactly', 'examines', 'exchange', 'exciting', 'execution', 'executive', 'exercise', 'exist', 'existed', 'existence', 'existentialism', 'exists', 'exorcism', 'exotic', 'exoticisland', 'expectations', 'expected', 'expects', 'expedition', 'experience', 'experienced', 'experiences', 'experiencing', 'experiment', 'expert', 'exploits', 'explorers', 'explores', 'exploring', 'explosion', 'explosive', 'expose', 'exposed', 'exposes', 'extra', 'extramaritalaffair', 'extraordinary', 'extraterrestrial', 'extraterrestrialtechnology', 'extreme', 'extremely', 'extremeviolence', 'eye', 'eyes', 'face', 'faced', 'faces', 'facility', 'facing', 'fact', 'factions', 'factory', 'fail', 'failed', 'failing', 'fails', 'fairy', 'fairytale', 'faith', 'fake', 'fall', 'fallen', 'falling', 'fallinginlove', 'falls', 'falseidentity', 'falselyaccused', 'fame', 'famed', 'families', 'family', 'familyconflict', 'familyrelationships', 'famkejanssen', 'famous', 'fan', 'fangvamp', 'fans', 'fantasies', 'fantastic', 'fantasy', 'fantasyworld', 'far', 'farewell', 'farm', 'farmer', 'farmhouse', 'fascinated', 'fashion', 'fast', 'faster', 'fat', 'fatal', 'fate', 'fateful', 'father', 'fatherdaughterrelationship', 'fathersonrelationship', 'favorite', 'fbi', 'fbiagent', 'fear', 'fearless', 'fears', 'fearsome', 'feature', 'features', 'featuring', 'federal', 'federation', 'feel', 'feeling', 'feelings', 'feels', 'feet', 'fellow', 'female', 'femalecorpse', 'femalefriendship', 'femalenudity', 'femaleprotagonist', 'festival', 'feud', 'fi', 'fiancee', 'fiancé', 'fiancée', 'fiction', 'fictional', 'fictionalplace', 'field', 'fields', 'fierce', 'fifth', 'fight', 'fighter', 'fighters', 'fighting', 'fights', 'figure', 'figures', 'filled', 'film', 'filmdirector', 'filmed', 'filming', 'filmmaker', 'filmmakers', 'filmmaking', 'filmproducer', 'films', 'final', 'finale', 'finally', 'financial', 'finding', 'finds', 'fine', 'finish', 'finn', 'fired', 'firm', 'fish', 'fisherman', 'fishing', 'fishoutofwater', 'fistfight', 'fit', 'fix', 'flame', 'flashback', 'flee', 'flees', 'flesh', 'flight', 'fling', 'flint', 'flirt', 'flood', 'florida', 'flower', 'fly', 'flying', 'flyingsaucer', 'focus', 'focuses', 'foi

In [58]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [59]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [60]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\PIYUSH\AppData\Local\Temp\ipykernel_15124\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [61]:
new_df['tags'].head()

0    in the 22nd century, a parapleg marin is dispa...
1    captain barbossa, long believ to be dead, ha c...
2    a cryptic messag from bond’ past send him on a...
3    follow the death of district attorney harvey d...
4    john carter is a war-weary, former militari ca...
Name: tags, dtype: object

In [62]:
features=cv.get_feature_names_out()
print(*features)

000 007 10 100 11 12 13 14 15 16 17 17th 18 18th 18thcentury 19 1930s 1940s 1950s 1960s 1970s 1980 1980s 1985 1990s 19th 19thcentury 20 200 2009 20th 24 25 30 300 3d 40 50 500 60 60s 70 aaron aaroneckhart abandoned abducted abigailbreslin abilities ability able aboard abuse abusive academy accept accepted accepts access accident accidental accidentally accompanied accomplish account accountant accused ace achieve act acting action actionhero actions activist activities activity actor actors actress acts actual actually adam adams adamsandler adamshankman adaptation adapted addict addicted addiction adolescence adopt adopted adoption adopts adrienbrody adult adultery adulthood adults advantage adventure adventures advertising advice affair affairs affection affections afghanistan africa african africanamerican aftercreditsstinger afterlife aftermath age aged agedifference agency agenda agent agents aggressive aging ago agree agrees ahead aid aided aids ailing air airplane airplanecrash airport aka al alabama alan alaska albert alcatraz alcohol alcoholic alcoholism alecbaldwin alex alexkendrick alfredhitchcock alfredmolina ali alice alien alieninvasion alienlife alienplanet aliens alike alive allen alliance allied allies allow allowing allows ally alongside alpacino alpha alter alternate alternative alyssa alzheimer amanda amandapeet amandaseyfried amateur amazing amazon ambassador ambition ambitious ambulance ambush america american americanabroad americancivilwar americanfootball americanfootballplayer americans amid amidst amnesia amp amsterdam amusement amusementpark amy amyadams amysmart ana anakin analyst anarchiccomedy ancient ancientrome ancientworld anderson andiemacdowell andrew android andy andygarcía angel angela angelabassett angeles angelinajolie angels anger anglee angry animal animalattack animalhorror animals animated animation anime anjelicahuston ann anna annabelle annafaris annakendrick anne annehathaway annemoss annettebening annie anniversary announces annual anonymity answer answers ant antarctic anthology anthony anthonyanderson anthonyhopkins anthonymackie anthropomorphism anti antics antihero antoinefuqua antoniobanderas antonyelchin apart apartheid apartment ape apes apocalypse apocalyptic apparent apparently appear appears apple appointed apprentice approach approaches approaching april aquarium arab arch archaeologist archeology archer architect arctic area aren arena argument arise aristocrat armed arms army arnold arnoldschwarzenegger arrangedmarriage arrest arrested arrival arrive arrives arriving arrogant art arthur artificialintelligence artist artistic artists arts ashley ashleyjudd ashtonkutcher asia aside ask asked asking asks aspirations aspiring assassin assassinate assassination assassins assault assigned assignment assistant assumes asteroid astronaut astronauts asylum athlete atomicbomb attack attacked attacks attempt attempting attempts attending attends attention attitude attorney attracted attraction attractive audience audiences audition august aunt austin australia australian author authorities authority autism auto avenge average avoid awaits awakens award away awry ax babe baby bachelor backdrop background backgrounds bad bag bahamas bail balance ball ballet baltimore band bandits bangkok banished bank banker bankrobber bankrobbery bar barely bargained barn barney barry barrylevinson bars base baseball based basedoncomicbook basedongraphicnovel basedonnovel basedonplay basedonstagemusical basedontrueevents basedontruestory basedontvseries basedonvideogame basedonyoungadultnovel basement basketball batman battle battlefield battles battling bay beach bear bears beast beasts beat beating beautiful beautifulwoman beauty becky becominganadult bed bedroom beer befriends began begin beginning begins behavior beings beliefs believe believed believes believing beloved ben benaffleck beneath benfoster beniciodeltoro benjamin benjaminbratt benkingsley bennett benstiller bent berlin best bestfriend bet beth betrayal betrayed bettemidler better betty beverly bible big bigger biggest biker bikini billhader billionaire billmurray billnighy billpaxton billpullman billy billybobthornton billycrudup billycrystal biography bird birth birthday bisexual bishop bit bite bitter bizarre black blackmagic blackmail blackpeople blade blame blind bliss block blonde blood bloodsplatter bloodthirsty bloody blow blue board boarding boardingschool boat bob bobby bobbyfarrelly bobhoskins bodies body bodyguard bold bollywood bomb bombing bond bonds bone book books border bored boredom boring born boss boston botched bound boundaries bounty bountyhunter box boxer boxing boy boyfriend boys bradleycooper bradpitt brain brand brave bravery brazil brazilian break breakdown breaking breaks brendanfraser brendangleeson brent brettratner brian briandepalma bride bridge brief brien bright brilliant bring bringing brings brink britain british britishsecretservice brittanymurphy broadway broke broken broker brooklyn brooks brothel brother brotherbrotherrelationship brothers brothersisterrelationship brought brown bruce brucewillis brutal brutality brutally bryansinger buck buddies buddy buddycomedy budget build building builds built bully bullying bumbling bunch bunker bunny burglar buried burned burns bus bush business businessman bust busy butcher butler butt buy buzz cabin caesar cage cairo cal california called calling calls calvin camcorder came camera cameraman cameras camerondiaz camp campaign campbell camping campus canada canadian cancer candidate candy canine cannibal canuxploitation capable caper capital capitalism capt captain captive capture captured captures car caraccident carchase carcrash card care career carefree cares caretaker careymulligan caribbean carjourney carl carlagugino carmen carnival carol carolina carrace carrie carry carrying cars cartel carter cartoon caryelwes case caseyaffleck cash casino cast castle cat cataclysm catastrophe catch catches cateblanchett catherinekeener catherinezeta catholic catholicism cattle caught cause caused causes causing cavalry cave celebrate celebrated celebration celebrity cellphone cemetery center centered centers central centuries century ceremony certain chain chainsaw challenge challenged challenges champion championship chance change changed changes changing channingtatum chaos chaotic chapter character characters charge charged charismatic charles charlie charliesheen charlizetheron charlotte charm charming chase chased chauffeur cheating cheerleader chef chemical cher chicago chicken chief child childabuse childhero childhood childprodigy children chilling china chinese chip chiwetelejiofor chloe chloëgracemoretz chloësevigny chocolate choice choices choose chosen chowyun chris chriscolumbus chriscooper chrisevans chrishemsworth chrisklein chrispine chrisrock christ christian christianbale christianity christianslater christinaapplegate christinaricci christine christmas christmasparty christmastree christopher christopherlambert christopherlloyd christophernolan christopherplummer christopherwalken christophwaltz chronicle chronicles chuck church cia cigarettesmoking cillianmurphy cinema circle circuit circumstances circus cities citizens city civil civilization civilwar claim claims claire clairedanes clan clark clash class classes classic classmate classmates classroom claudevandamme clay clean clear clerk client clients climate climbing clinteastwood cliveowen clock clone cloning close closer club clubs clues clutches coach coast cocaine cocky code cody coffin cohen col cold coldwar cole colin colinfarrell colinfirth collapse colleague colleagues collect collection collector college collide collision colonel colony color colorado colorful coma combat combined come comeback comedian comedic comedy comes comet comfort comic comics coming comingofage comingout command commander commercial commit commitment committed common communication community companion company compete competing competition complete completely complex complicated complications composer computer computervirus conan concert conclusion condition confession confidence confident conflict confront confronted confused congress conman connected connection connell connor conquer conscience consequences conservative considered conspiracy constant constantly construction contact contain contemporary contend contest continue continues continuing contract control controlled controlling controversial convention converge convict convicted convince convinced convinces cook cooking cool cooper cop cope cops core corner corners corporate corporation corpse corrupt corruption cost costume couldn count countess countless countries country countryhouse countrymusic countryside county coup couple couples courage courageous course court courtcase courteneycox courtroom cousin cover covert cow cowardliness cowboy crab crack craft craig crane crash crashes crashing crazy create created creates creation creator creature creatures credit creepy crew crime crimefighter crimes criminal criminals crisis critical crocodile crook crooked cross crossed crosses crown cruel cruelty cruise crush crystal cuba cubagoodingjr cult cultfilm cultural culture cultureclash cunning cup cure curious current curse cursed custody customers cut cyberpunk cyborg dad daily dakotafanning damage dan danaykroyd dance dancer dancing danger dangerous dangers daniel danielcraig danielday danielradcliffe danny dannyboyle dannydevito dannyglover darcy dare daring dark darkcomedy darkest darkness darylhannah dashing date dates dating daughter daughters dave david davidarquette davidcronenberg davidduchovny davidfincher davidgordongreen davidmorse davido davidschwimmer davis daxshepard day days dc dccomics dea dead deadly deaf deal dealer dealers dealing deals dean death deathofafriend deathpenalty deaths debt debut decade decades decapitation deceased deceit deception decide decided decides decision decisions dedicated deeds deep deeper deeply defeat defend defense deliver delivers delusion demanding demands demimoore demon demonic demonicpossession demons dennisdugan dennishopper dennisquaid dentist denzelwashington department depressed depression deputy deranged derek descend desert deserted designed desire desires desolate despair desperate desperately desperation despite destined destiny destroy destroyed destroying destruction destructive details detective detectives detention determination determine determined detroit devastating develop developed developer developing develops device devil devious devoted diabolical diagnosed dialogue diamond diane dianekeaton dianekruger dianelane diary dick dictator did didn die died diego dies differences different difficult digging dignity diner dinner dinosaur dinosaurs dire directed direction director dirt dirty dirtycop disabled disappearance disappeared disappears disaster disastrous discover discovered discovering discovers discovery disease disfigurement disgraced disguise dishonesty disillusioned disney disorder dispatched distant district distrust disturbed disturbing diva divided division divorce divorced dna doc doctor document documentary documents does doesn dog dogs doing doll dollar dollars dolphin dolphlundgren domination don donaldpetrie donaldsutherland doncheadle donnell doomed doomsday door doorstep doppelganger dorothy double doublelife doubt doubts doug douglas dougliman dr dracula drag dragon drama dramatic draw drawing drawn draws dream dreams drew drewbarrymore drifter drink drinking drive driven driver drives driving drop drowning drug drugabuse drugaddiction drugdealer druglord drugs drugtraffic drunk drunken du dualidentity dude duel duke dumped duo duringcreditsstinger dustinhoffman dutch duty dwarves dwaynejohnson dying dyinganddeath dylan dynamic dynasty dysfunctional dysfunctionalfamily dystopia dystopicfuture eager earlier early earn earth earthquake east easy eating eccentric economic economy eddie eddiegriffin eddiemurphy edge edharris editor education edward edwardburns edwardnorton effort efforts egg ego egypt egyptian el elaborate elderly election elements eliaskoteas elijahwood eliminate elisabethshue elite elizabeth elizabethbanks ella ellenburstyn ellenpage ellie elliot ellis elusive elves elvis embark embarking embarks embassy embroiled emerge emergency emerges emilehirsch emily emilyblunt emilymortimer emilywatson emma emmastone emmathompson emmawatson emotional emotionally emotions emperor empire employee employees employer employs encounter encounters end ended ending endless endoftheworld ends enemies enemy energy enforcement engaged engagement engineer england english enigmatic enjoy enlist enlists enormous ensemblecast ensues entangled enter enterprise enters entertainer entertaining entire entirely entity environment environmental epic epidemic era eric ericbana erin ernest eroticism erupts escapade escape escaped escapes escaping escort especially espionage establishment estate estranged eternal ethan ethanhawke europe european eva evacuation evamendes evanrachelwood eve evening event events eventually everybody everyday evidence evil evolution ewanmcgregor ex exact exactly examines exchange exciting execution executive exercise exist existed existence existentialism exists exorcism exotic exoticisland expectations expected expects expedition experience experienced experiences experiencing experiment expert exploits explorers explores exploring explosion explosive expose exposed exposes extra extramaritalaffair extraordinary extraterrestrial extraterrestrialtechnology extreme extremely extremeviolence eye eyes face faced faces facility facing fact factions factory fail failed failing fails fairy fairytale faith fake fall fallen falling fallinginlove falls falseidentity falselyaccused fame famed families family familyconflict familyrelationships famkejanssen famous fan fangvamp fans fantasies fantastic fantasy fantasyworld far farewell farm farmer farmhouse fascinated fashion fast faster fat fatal fate fateful father fatherdaughterrelationship fathersonrelationship favorite fbi fbiagent fear fearless fears fearsome feature features featuring federal federation feel feeling feelings feels feet fellow female femalecorpse femalefriendship femalenudity femaleprotagonist festival feud fi fiancee fiancé fiancée fiction fictional fictionalplace field fields fierce fifth fight fighter fighters fighting fights figure figures filled film filmdirector filmed filming filmmaker filmmakers filmmaking filmproducer films final finale finally financial finding finds fine finish finn fired firm fish fisherman fishing fishoutofwater fistfight fit fix flame flashback flee flees flesh flight fling flint flirt flood florida flower fly flying flyingsaucer focus focuses foil follow followed following follows food foot footage football footchase forbidden forbiddenlove force forced forces forcing ford foreign forest forestwhitaker forever forget forgiveness form formidable forms formula fort fortune fortuneteller forward foster fought foundfootage fourth fox framed france franchise francis francisco francisfordcoppola frank frankenstein frankie frankoz fraternity fraud freak fred freddieprinzejr freddy free freedom french fresh freshman friend friendly friends friendship frightening frog frontier frozen frustrated fu fugitive fulfill fully fun fund funeral funny furious future futuristic fword gabrielbyrne gaelgarcíabernal gain galaxy gambler gambling game games gandhi gang gangs gangster gangsterboss gangsters gangwar garage garden garfield garrymarshall gary garygray garyoldman garysinise gas gasstation gather gave gay gayrelationship genehackman general generation generations genetic genetically genetics genius gentle geoffreyrush george georgeclooney georgia gerardbutler german germans germany getaway gets getting ghetto ghost ghosts giant giants gift gifted gig girl girlfriend girlfriends girls given gives giving gladiator glamorous glass global globe glory goal god gods goes going gold golden golf gone good goodvsevil gordon gore gorgeous gorilla gossip got gotham gothamcity government governor grace grade gradually graduate graduation grand grandfather grandmother grant graphic grave great greater greatest greece greed greedy greek green greg gregkinnear gregorypeck grew grief grieving griffin grim grip grisly gritty ground group groupoffriends grow growing growingup grown grows gruesome guard guardian guerrilla guest guests guide guilt guilty guitar gun gunfight gunman guns gunslinger guru gusvansant guy guypearce guys gwynethpaltrow gym hacker hacking hair haleyjoelosment half hall halleberry halloween hallucination hand handed hands handsome handtohandcombat hang hanging hangs hannah happen happened happening happens happily happiness happy hara harbor hard harlem harmony harold haroldramis harrisonford harry harsh hart harvard harvey harveykeitel hasn hatches hate hatred haunt haunted hauntedhouse haunting haven having havoc hawaii hawkins haydenchristensen head headed heading headquarters heads healing health hear hearing hears heart heartbreak hearted hearts heather heathledger heaven heavily heavy heavymetal heir heiress heist held helen helenabonhamcarter helenhunt helenmirren helicopter hell help helped helping helps henchmen henry hero heroes heroic heroin heroism hidden hiddencamera hide hides hiding high higher highest highlands highly highschool highschoolsports highschoolstudent highway hijack hijacking hilarious hilaryduff hilaryswank hill hills himalaya hip hippie hire hired hires historic historical historicalfigure history hit hitchhiker hitman hits ho hockey hold holding holds hole holiday hollywood home homeinvasion homeland homeless homelessperson hometown homicidal homicide homosexuality honey honeymoon hong hongkong honor hood hoodlum hook hop hope hopedavis hopelessly hopes hoping hopper horrible horrific horrifying horror horrors horse hospital host hostage hostile hostility hot hotel hotelroom hour hours house housekeeper housewife housing howard huge hughgrant hughjackman human humananimalrelationship humanity humankind humans humiliation humor hundreds hunger hungry hunt hunted hunter hunters hunting hurricane husband hustler hypnosis hyun ianmckellen ice icecube iconic idea idealistic ideas identities identity idol idyllic ignoring ii iii il ill illegal illegalimmigration illegalprostitution illness image imaginary imagination imagined imax immediately immigrant immigrants immigration immortal immortality impact imperial important impossible imprisoned imprisonment inadvertently incest incident include includes including increasingly incredible independence independent independentfilm india indian indiana indianlead indians indie individual industry inexplicably infamous infant infected infection infidelity infiltrate influence informant information inhabitants inheritance inherited inherits initially injured injury injustice inmates inner innocence innocent insane insanity inside insists insomnia inspector inspiration inspire inspired inspires inspiring installment instant instantly instead institution instructor insurance intelligence intelligent intends intense intent intentions intergalactic international internet interrogation interspeciesromance intertwine interview interviews intimate intrigue introduces invaders invading invasion invention inventor investigate investigates investigating investigation investigator investment invisible invites involved involves involving iowa ira iran iranian iraq ireland irish island isn isolated isolation israel israeli issues italian italy ivanreitman jack jackblack jackie jackiechan jacknicholson jackson jadapinkettsmith jail jake jakegyllenhaal james jamescaan jamesfranco jamesmangold jamesmarsden jamesmcavoy jameswoods jamie jamiefoxx jamieleecurtis jane japan japanese jason jasonbateman jasonbiggs jasonlee jasonsegel jasonstatham javierbardem jay jayroach jazz jealous jealousy jean j

In [63]:
ps.stem('in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi scienc fiction cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi scienc fiction cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [64]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi scienc fiction cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [65]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000 , stop_words='english')

In [66]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [67]:
features = cv.get_feature_names_out()
print(*features)

000 007 10 100 11 12 13 14 15 16 17 18 18th 18thcenturi 19 1910 1920 1930 1940 1944 1950 1950s 1960 1960s 1970 1970s 1974 1976 1980 1985 1990 1999 19th 19thcenturi 20 200 2003 2009 20th 21st 23 24 25 30 300 3d 40 50 500 60 70 80 aaron aaroneckhart abandon abduct abigailbreslin abil abl aboard abov abus academ academi accept access accid accident acclaim accompani accomplish account accus ace achiev acquaint act action actionhero activ activist activities actor actress actual ad adam adamsandl adamshankman adapt add addict adjust admir admit adolesc adopt ador adrienbrodi adult adultanim adulteri adulthood advanc adventur adventure adventures advertis advic advis affair affect afghanistan africa african africanamerican aftercreditssting afterlif aftermath ag age agediffer agenc agency agenda agent agents aggress ago agre ahead aid aidanquinn ail aim air airplan airplanecrash airport aka al alabama alan alaska albert alcatraz alcohol alecbaldwin alex alexkendrick alfredhitchcock alfredmolina ali alic alice alien alieninvas alienlife alienplanet aliens alik aliv alive allen alli allianc allow alon alongsid alpacino alpha alreadi alter altern alway alyssa alzheimer amanda amandapeet amandaseyfri amateur amaz amazon ambassador ambit ambiti ambul ambush america american americanabroad americancivilwar americanfootbal americanfootballplay amid amidst amnesia amp amsterdam amus amusementpark amy amyadam amysmart ana anakin analyst anarchiccomedi ancient ancientrom ancientworld anderson andi andiemacdowel andrew android andy andygarcía angel angela angelabassett angeles angelinajoli anger angle angri ani anim animalattack animalhorror animals anjelicahuston ann anna annafari annakendrick anne annehathaway annemoss annetteben anni annie anniversari announc annual anonym anoth answer ant antholog anthoni anthonyanderson anthonyhopkin anthonymacki anthropomorph anti antic antihero antiqu antoinefuqua antoniobandera antonyelchin anyon anyth apart apartheid apartment ape apocalyps apocalypse apocalypt appar appear appl apple appoint appreci apprentic approach april aquarium arab arch archaeologist archeolog archer architect arctic area aren arena argument aris aristocrat arm armi armor armsdeal army arnold arnoldschwarzenegg arrang arrangedmarriag arrest arriv arrog art arthur artifact artifici artificialintellig artist ash ashley ashleyjudd ashtonkutch asia asian asid ask aspect aspir assassin assault assembl assign assist assistant associ assum asteroid astronaut asylum atheist athlet atom atomicbomb attack attacks attempt attempttoescap attend attent attic attitud attorney attract auction audienc audit august aunt austin australia australian author autism auto automobilerac aveng averag avoid await awak awaken awar award away awkward awri awry ax babe babi baby bachelor backdrop background backpack bad bag bahama bail balanc ball ballet balloon baltimor ban band bandit bangkok banish bank banker bankrobb bankrobberi bar barbrastreisand bare bargain barn barney baron barri barrylevinson barrysonnenfeld bas base basebal basedoncomicbook basedongraphicnovel basedonnovel basedonplay basedonstagemus basedontrueev basedontruestori basedontvseri basedonvideogam basedonyoungadultnovel basement basketbal basketball bat batman battl battle battlefield bay beach beam bear beard beast beat beauti beautiful beautifulwoman beauty becam becaus becki becom becominganadult bed bedroom bee beer befor befriend began begin begins behavior belief believ bell bella belong belov ben benaffleck bend beneath benefit benfost beniciodeltoro benjamin benjaminbratt benkingsley bennett benstil bent berlin best bestfriend bestfriendsinlov bet beth betray bettemidl better betti beverli bibl bid big bigger biggest bike biker bikini billhad billi billionair billmurray billnighi billpaxton billpullman billybobthornton billycrudup billycryst biographi biolog bird birth birthday bisexu bishop bit bite bitter bizarr black blackmag blackmail blackpeopl blacksmith blade blame blend blind bliss blizzard block blond blood bloodi bloodsplatt bloodthirsti blow blue board boardingschool boat bob bobbi bobbyfarrelli bobhoskin bodi body bodyguard bold bollywood bomb bond bone book border bore boredom born boss boston botch bound boundari bounti bountyhunt bout box boxer boy boyfriend boys bradleycoop bradpitt brain brainwash brand brandon brave braveri brazil brazilian break breakdown breakup breast breath breed brendanfras brendangleeson brent brettratn brian briandepalma bride bridesmaid bridg brief brien bright brilliant bring brink britain british britishsecretservic brittanymurphi broadcast broadway broke broken broker bronx brook brooklyn broom brothel brother brotherbrotherrelationship brothers brothersisterrelationship brought brown bruce brucegreenwood brucewilli brutal bryansing bu buck bud buddi buddy buddycomedi buddycop budget build building built bullet bulli bumbl bunch bunker bunni burglar buri burn bush busi business businessman bust butcher butler butt button buy buzz cabin caesar cage cairo cal california calvin camcord came camera cameraman camerondiaz camp campaign campbell campu canada canadian cancer candi candid canin cannib canuxploit capabl caper capit capt captain captiv captur capture car caraccid carchas carcrash card care career carefre caretak careymulligan caribbean carjourney carl carlagugino carmen carol carolina carrac carri carrie cartel carter cartoon caryelw case caseyaffleck cash casino cast castl cat cataclysm catastroph catch cateblanchett catherinedeneuv catherinekeen catherinezeta cathol catholic cattl caught caus cavalri cave cavemen celebr celebration cell cellphon cemeteri center centr central centuri centuries century ceo certain chad chain chainsaw challeng chamber champion championship chanc chance chang change changed changes channingtatum chao chaos chaotic chapter charact character characters charg charismat charl charli charlie charliesheen charlizetheron charm chart chase chauffeur chazzpalminteri cheat check cheerlead chef chemic cher chevychas chicago chicken chief child childabus childhero childhood childprodigi children chill chimp china chines chip chipmunk chiwetelejiofor chloe chloëgracemoretz chloësevigni chocol choic choice choos chosen chowyun chri chriscolumbu chriscoop chrisevan chrishemsworth chrisklein chrispin chrisrock christ christian christianbal christianslat christin christinaappleg christinaricci christma christmas christmasparti christmastre christoph christopherlambert christopherlloyd christophernolan christopherplumm christopherwalken christophwaltz chrisweitz chronicl chuck church cia ciaránhind cigarettesmok cillianmurphi cinema circl circu circuit circumst citi citizen city civil civilian civilwar claim clair clairedan claireforlani clan clark clash class classdiffer classic classmat classroom claudevandamm clay clean clear clerk clever client clients cliff climat climb clinteastwood cliveowen clock clone close closer cloud clown club clue clueless clutch coach coast cocain code coffin cohen col cold coldwar cole colin colinfarrel colinfirth collaps colleagu collect collector colleg college collid collis colombia colonel coloni color colorado coma combat combin come comeback comed comedi comedian comedy comet comfort comic coming comingofag comingout command commando commerci commiss commit common commun communist community compani companion company compet competit competition complet complex complic compos compuls comput computerviru conan concern concert concoct condit condition conduct confeder confess confid confin conflict confront confus congress conman connect connecticut connel connor conquer consequ consequences conserv consid conspir conspiraci conspiracy constant constantli construct consum contact contain contemporari contend content contest continu contract contractor control controversi convent converg convers convict convinc cook cool cooper cop cope cops core corner corp corpor corporation corps corrupt cost costum couldn counselor count countess countless countri country countryhous countrymus countrysid coup coupl couple courag cours court courtcas courteneycox courtroom cousin cover covert covet cow cowardli cowboy crab crack craft craig crane crash crave crazi creat creation creativ creator creatur creature creatures credit creepi crew cri crime crimefight crimes crimin criminal criminals crisi crisis critic crocodil crook cross crowd crown crucifixion cruel cruelti cruis crusad crush crystal cuba cubagoodingjr culmin cult cultfilm cultur culture cultureclash cun cup cure current curs curse curtishanson custodi custom cut cuttingthecord cyberpunk cyborg cynic dad daili dakotafan dale damag damon dan danaykroyd danc dancer danger daniel danielcraig danielday danielradcliff danni danny dannyboyl dannydevito dannyglov dare dark darkcomedi darkest darkness darylhannah dash date daughter daughters dave davi david davidarquett davidcronenberg davidduchovni davidfinch davidgordongreen davidmors davido davidschwimm davidspad davidthewli dawn daxshepard day daydream days dc dccomic dea dead deadli deadliest deaf deal dealer dean death deathofafriend deathoffath deathpenalti debt debut decad decapit deceas deceit decept decid decis declar dedic deed deep deeper deepli defeat defend defens defi defin delight deliv deliveri delus demand demimoor demon demonicpossess demons deni deniserichard denmark denni dennisdugan dennishopp dennisquaid dentist denzelwashington depart depend depict depress depth deputi derang derek derekluk descend describ desert design desir desk desol despair desper despit destin destini destiny destroy destroyed destruct destruction detect detective determin detroit devast develop devic devil deviou devis devot diabol diagnos dialogu diamond dian dianekeaton dianekrug dianelan diari dick dictat did didn die died diego dies differ different difficult difficulti dig dilemma diner dinner dinosaur diplomat dire direct director dirt dirti dirtycop disabl disappear disappears disast disaster disastr discov discoveri diseas disease disfigur disgrac disguis dishonesti disillus disney disord dispatch disrupt distant district distrust disturb ditch diva dive divid divis divorc divorce dj dna doc doctor document documentari dodg doe doesn dog doll dollar dolphin dolphlundgren domest domin don donaldpetri donaldsutherland doncheadl donnel doom doomsday door doorstep doppelgang dorothi doubl double doublecross doublelif doubt doug dougliman dr dracula drag dragon drama dramat draw drawn dread dream dreams dress drew drewbarrymor drift drifter drink drive driven driver drone drop drown drug drugabus drugaddict drugdeal druglord drugs drugsmuggl drugtraff drugus drunk drunken du dualident dub duck dude duel duke dump duo dure duringcreditssting dustinhoffman dutch duti dwarv dwaynejohnson dyinganddeath dylan dynam dynasti dysfunct dysfunctionalfamili dystopia dystopicfutur eager earli earlier earn earth earthquak easi easili east eat eccentr econom economi eddi eddiegriffin eddiemurphi edg edgar edharri editor educ edward edwardburn edwardnorton edwardzwick effect effort egg ego egypt egyptian el elabor elderli elect element eleph elev eliaskotea elijahwood elimin elisabethshu elit elite elizabeth elizabethbank ella ellenburstyn ellenpag elli elliot elliott els elud elus elv elvi embark embassi embroil emerg emigr emilehirsch emili emilyblunt emilymortim emilywatson emma emmarobert emmaston emmathompson emmawatson emot emperor empir empire employ employe employer enabl enchant encount encourag end endless endoftheworld endur enemi enemies enemy energi enforc engag engin england english enigmat enjoy enlist enorm enrol ensemblecast ensu ensues ensur entangl enter enterpris entertain enthusiast entir entiti environ environment epic epidem episod equal era eric ericbana erin ernest erotic erupt escap escapad escape escapefromprison escort especi espionag establish estat estrang etern ethan ethanhawk ethic eugenelevi europ european eva evacu evad evamend evanrachelwood eve event events eventu eventually everi everybodi everyday everyon everyth evid evil evolut evolv ewanmcgregor ex exact exactli exam examin exchang excit exclus execut exercis exhibit exil exist existence existenti exorc exot exoticisland expect expected expedit experi experienc experience experiment expert explain explod exploit explor explos expos extend extra extramaritalaffair extraordinari extraterrestri extraterrestrialtechnolog extrem extremeviol eye eyes fabl fac face facil fact faction factori fade fail fairi fairytal faith fake falcon fall fallen fallinginlov fals falseident falselyaccus fame famili families family familyconflict familyrelationship famkejanssen famou fan fangvamp fans fantasi fantast fantasyworld far farewel farm farmer fascin fashion fast faster fat fatal fate father fatherdaughterrelationship fathersonrelationship favor favorit fbi fbiagent fear fearless fearsom featur fed feder feed feel feet fellow femal female femalecorps femalefriendship femalenud femaleprotagonist fend festiv festival fetish feud fi fiance fiancé fiction fictionalplac field fierc fifth fight fighter figur fil file film filmdirector filmmak filmproduc films final finale financ financi fine finish finn firemen firework firm firsttim fish fisherman fishoutofwat fistfight fit fix flame flash flashback flat fledgl flee flesh fli flight fling flint flirt flood florida florist flower flyingsauc focu focus foe foil foley folk follow food foot footag footbal footchas forbidden forbiddenlov forc force forces ford foreign forest forestwhitak forev forever forg forget forgiv form formid formula fort fortun fortune fortunetel forward foster fought foundfootag fourth fox frame franc france francisco francisfordcoppola frank frankcoraci frankenstein franki frankoz frantic fratern fraud freak fred freddi freddieprinzejr free freedom freeman freez french frequent fresh freshman friend friendli friends friendship frighten frog fromragstorich frontier frozen frustrat fu fuel fugit fulfil fulli fun fund funer funeral furiou futur future futurist fword ga gabriel gabrielbyrn gadget gaelgarcíabern gain galaxi galaxy gambl gambler game games gandhi gang gangs gangster gangsterboss gangwar garag garden garfield gari garrymarshal garygray garyoldman garysinis gasstat gate gather gave gay gayinterest gayrelationship genehackman gener general generation genet geniu genius gentl geoffreyrush georg george georgea georgeclooney georgemil georgia gerardbutl german germani germany getaway ghetto ghost giant giantrobot gift gig girl girlfriend girls given glamor glass glennclos global globe glori goal god goe gold golden golf gone good goodvsevil gordon gore goreverbinski gorgeou gorilla gossip got gotham gothamc gotten govern government governor grace grad grade gradual graduat grand grandfath grandfather grandmoth grandmother grant graphic grasp grave great greater greatest greec greed greedi greek green greg gregkinnear gregorypeck grew grief griev griffin grim grip grisli ground group groupoffriend grow growingup grown gruesom gu guard guardian guerrilla guest guid guilt guitar gun gunfight gunman gunsling guru gusvans guy guypearc guyritchi guys gwynethpaltrow gym gypsi ha hack hacker hair haleyjoelos half hall halleberri halloween hallucin han hand handl hands handsom handtohandcombat hang hangov hannah hansel hapless happen happens happi happili happiness happy hara harass harbor hard harder harlem harmoni harold haroldrami harri harriet harrison harrisonford harrow harry harsh hart harvard harvey harveykeitel hasn hatch hate haunt hauntedhous haven havoc hawaii haydenchristensen haze head headlin heal health hear heard heart heartattack heartbreak heat heather heathergraham heathledg heaven heavi heavili heavymet height heir heiress heist held helen helenabonhamcart helenhunt helenmirren helicopt hell help henchmen henri hero heroes heroic heroin heroism hi hidden hiddencamera hide high higher highest highland highli highschool highschoolsport highschoolstud highway hijack hike hilari hilaryduff hilaryswank hill himalaya hip hippi hire histor histori historicalfigur history hit hitch hitchhik hitman ho hobbit hockey hold hole holi holiday holli hollywood home homeinvas homeland homeless homelessperson hometown homicid homophobia homosexu honey honeymoon hong hongkong honor hood hoodlum hook hop hope hopedavi hopelessli hopper hord horribl horrif horrifi horror hors horsebackrid horserac hospit hospital host hostag hostage hostil hot hotel hotelroom hotshot hour hous house household housewif howard howev hud huge hugh hughgrant hughjackman human humananimalrelationship humanity humankind humans humili humor hundr hunger hungri hunt hunter hunters hurrican hurt husband hustler hypnosi hypnot hyster hyun ianmckellen ice icecub icon idea ideal idealist ident identity idol idyl ignit ignor ii iii il ill illeg illegaldrug illegalimmigr illegalprostitut illness illus illustr imag imagin imaginari imagined imax immedi immens immigr immort impact imperi imperson implic import imposs impostor impress imprison inadvert incest incid includ incompet increas increasingli incred independ independentfilm indi india indian indiana indianlead individu industri industry inevit inexplic infam infant infect infidel infiltr influenc inform inhabit inherit initi inject injur injuri inmat inner innoc insan insecur insid insight insist insomnia inspector inspir instal instant instantli instead instinct institut institution instructor insur insurg intellig intend intens intent intergalact intern internet interpret interrog interspeciesrom intertwin interview intim intoler intrigu introduc invad invas invent inventor invest investig investigate invis invit involv iowa ira iran iranian iraq iraqwar ireland irish iron islam island isn isol isra israel issu itali italian ivanreitman jack jackass jackblack jacki jackiechan jacknicholson jackson jacob jadapinkettsmith jade jail jake jakegyllenha jamaica jame james jamescaan jamescameron jamesfranco jamesivori jamesmangold jamesmarsden jamesmcavoy jameswan jameswood jami jamie jamiefoxx jamieleecurti jan jane janitor japan japanes jaredleto jason jasonbateman jasonbigg jasonle jasonschwartzman jasonsegel jasonstatham javierbardem jay jaychandrasekhar jayroach jazz jealousi jean jeanreno jedi jeff jeffbridg jeffdaniel jeffgoldblum jeffreywright jennif jenniferaniston jenniferconnelli jennifergarn jenniferjasonleigh jenniferlawr jenniferlopez jenniferlovehewitt jeremyiron jeremyrenn jerri jersey jerusalem jess jessebradford jesseeisenberg jessica jessicaalba jessicabiel jessicachastain jesu jesus jesuschrist jetli jew jewel jewish jigsaw jill jim jimbroadb jimcarrey jimcaviezel jimmi jimmy jin joanallen joancusack joaquinphoenix job jobinterview jock jodiefost joe joel joelcoen joeledgerton joelschumach joepesci joey john johnc johncarpent johncusack johngoodman johnhurt johnkrasinski johnleguizamo johnmalkovich johnmctiernan johnni johnny johnnydepp johnnyknoxvil johnsingleton johnson johntravolta johnturturro johnwoo join jon jonahhil jonathan jonathanfrak jonathanrhysmey jone jones jonfavreau jonturteltaub jonvoight jordan joseph josephgordon josh joshbrolin joshhartnett joshhutcherson journal journalist journey joy jr juan judelaw judg judidench juli julia julian juliannemoor juliarobert juliastil julie jump jungl jungle junior junki just justic justice justinlong justintimberlak kansa karat karen karlurban kat kate katebeckinsal katebosworth katehudson katemara katewinslet katherin katherineheigl kathi kathyb kati katieholm katniss kay keanureev keiraknightley kelli kelly kellypreston ken kennethbranagh kermit kevin kevinbacon kevincostn kevinhart kevinjam kevinklin kevinsmith kevinspacey key kgb khan kick kid kidnap kidnapp kidnapped kids kidsandfamili kiefersutherland kill killed killer killerrobot killers kim kimbasing kind king kingdom kingpin kirk kirstendunst kiss kit kitchen knew knife knight knit knock know 

In [68]:
from sklearn.metrics.pairwise import cosine_similarity

In [69]:
similarity=cosine_similarity(vectors)

In [70]:
cosine_similarity(vectors).shape

(4805, 4805)

In [71]:
list(enumerate(similarity[1]))

[(0, np.float64(0.08238525545716345)),
 (1, np.float64(1.0)),
 (2, np.float64(0.06063390625908323)),
 (3, np.float64(0.03883678186903086)),
 (4, np.float64(0.07426106572325057)),
 (5, np.float64(0.1145873121285264)),
 (6, np.float64(0.02127178149057585)),
 (7, np.float64(0.1278274981412284)),
 (8, np.float64(0.06262242910851494)),
 (9, np.float64(0.10226199851298272)),
 (10, np.float64(0.10713431680111603)),
 (11, np.float64(0.07504691899113898)),
 (12, np.float64(0.4140043409440133)),
 (13, np.float64(0.09513029883089881)),
 (14, np.float64(0.13391789600139503)),
 (15, np.float64(0.1107018606925119)),
 (16, np.float64(0.08238525545716345)),
 (17, np.float64(0.2533201985524494)),
 (18, np.float64(0.059808916712167495)),
 (19, np.float64(0.1097907187727647)),
 (20, np.float64(0.061357199107789626)),
 (21, np.float64(0.05797710356524483)),
 (22, np.float64(0.10502100630210075)),
 (23, np.float64(0.09240616554505461)),
 (24, np.float64(0.14097096860865022)),
 (25, np.float64(0.1078676197944929)),
 (26, np.float64(0.10713431680111603)),
 (27, np.float64(0.08712136837380642)),
 (28, np.float64(0.06063390625908323)),
 (29, np.float64(0.04583492485141056)),
 (30, np.float64(0.11778571185788637)),
 (31, np.float64(0.09901475429766741)),
 (32, np.float64(0.09007546982220897)),
 (33, np.float64(0.10090091909944686)),
 (34, np.float64(0.03300491809922247)),
 (35, np.float64(0.10289915108550529)),
 (36, np.float64(0.07669649888473704)),
 (37, np.float64(0.05564148840746572)),
 (38, np.float64(0.12862393885688161)),
 (39, np.float64(0.057166195047502935)),
 (40, np.float64(0.08134892168199606)),
 (41, np.float64(0.09901475429766743)),
 (42, np.float64(0.0)),
 (43, np.float64(0.07134772412317411)),
 (44, np.float64(0.03575992699260758)),
 (45, np.float64(0.06431196942844081)),
 (46, np.float64(0.11595420713048966)),
 (47, np.float64(0.12387602085230007)),
 (48, np.float64(0.11163607017227663)),
 (49, np.float64(0.03080205518168487)),
 (50, np.float64(0.08956221510397981)),
 (51, np.float64(0.04190377370950561)),
 (52, np.float64(0.07669649888473704)),
 (53, np.float64(0.11357771260606365)),
 (54, np.float64(0.03300491809922247)),
 (55, np.float64(0.07440653318043244)),
 (56, np.float64(0.07312724241271305)),
 (57, np.float64(0.15339299776947407)),
 (58, np.float64(0.09513029883089881)),
 (59, np.float64(0.09527699174583823)),
 (60, np.float64(0.0)),
 (61, np.float64(0.13719886811400706)),
 (62, np.float64(0.13284223283101426)),
 (63, np.float64(0.06482037235521643)),
 (64, np.float64(0.03080205518168487)),
 (65, np.float64(0.020646003475383347)),
 (66, np.float64(0.11891287353862351)),
 (67, np.float64(0.056388387443460086)),
 (68, np.float64(0.0939336436627724)),
 (69, np.float64(0.0700140042014005)),
 (70, np.float64(0.05292561240249631)),
 (71, np.float64(0.10341753799900383)),
 (72, np.float64(0.11433239009500587)),
 (73, np.float64(0.03500700210070025)),
 (74, np.float64(0.07067142711473183)),
 (75, np.float64(0.16477051091432687)),
 (76, np.float64(0.05003127932742599)),
 (77, np.float64(0.04565411576455765)),
 (78, np.float64(0.053567158400558014)),
 (79, np.float64(0.10890171046725802)),
 (80, np.float64(0.03556714970147893)),
 (81, np.float64(0.09709195467257715)),
 (82, np.float64(0.026462806201248155)),
 (83, np.float64(0.07067142711473183)),
 (84, np.float64(0.08712136837380642)),
 (85, np.float64(0.12004900959975617)),
 (86, np.float64(0.05003127932742599)),
 (87, np.float64(0.028988551782622416)),
 (88, np.float64(0.0955394632947723)),
 (89, np.float64(0.04565411576455765)),
 (90, np.float64(0.09723055853282464)),
 (91, np.float64(0.1449427589131121)),
 (92, np.float64(0.06587443126365883)),
 (93, np.float64(0.049507377148833714)),
 (94, np.float64(0.16205093088804107)),
 (95, np.float64(0.04899959575500252)),
 (96, np.float64(0.08035073760083702)),
 (97, np.float64(0.09701425001453318)),
 (98, np.float64(0.13231403100624078)),
 (99, np.float64(0.056388387443460086)),
 (100, np.float64(0.03575992699260758)),
 (101, np.float64(0.08035073760083702)),
 (102, np.float64(0.06534102628035482)),
 (103, np.float64(0.0844400661841498)),
 (104, np.float64(0.14705882352941174)),
 (105, np.float64(0.10969086361906957)),
 (106, np.float64(0.13174886252731766)),
 (107, np.float64(0.06534102628035482)),
 (108, np.float64(0.049507377148833714)),
 (109, np.float64(0.17149858514250882)),
 (110, np.float64(0.023782574707724703)),
 (111, np.float64(0.07845986714489121)),
 (112, np.float64(0.05423261445466404)),
 (113, np.float64(0.04583492485141056)),
 (114, np.float64(0.04850712500726659)),
 (115, np.float64(0.09249945801257606)),
 (116, np.float64(0.05003127932742599)),
 (117, np.float64(0.0939336436627724)),
 (118, np.float64(0.017783574850739465)),
 (119, np.float64(0.04583492485141056)),
 (120, np.float64(0.0)),
 (121, np.float64(0.11764705882352938)),
 (122, np.float64(0.12126781251816646)),
 (123, np.float64(0.04711428474315455)),
 (124, np.float64(0.09513029883089881)),
 (125, np.float64(0.0964256849261258)),
 (126, np.float64(0.11277677488692017)),
 (127, np.float64(0.11504474832710557)),
 (128, np.float64(0.028583097523751468)),
 (129, np.float64(0.14699878726500756)),
 (130, np.float64(0.057166195047502935)),
 (131, np.float64(0.08346223261119858)),
 (132, np.float64(0.07134772412317411)),
 (133, np.float64(0.05970814340265321)),
 (134, np.float64(0.06859943405700353)),
 (135, np.float64(0.0)),
 (136, np.float64(0.09901475429766743)),
 (137, np.float64(0.015923243882462048)),
 (138, np.float64(0.16269784336399212)),
 (139, np.float64(0.0850871259623034)),
 (140, np.float64(0.047565149415449405)),
 (141, np.float64(0.03080205518168487)),
 (142, np.float64(0.08956221510397981)),
 (143, np.float64(0.11458731212852641)),
 (144, np.float64(0.05292561240249631)),
 (145, np.float64(0.06105941257599791)),
 (146, np.float64(0.017149858514250882)),
 (147, np.float64(0.05882352941176469)),
 (148, np.float64(0.06859943405700353)),
 (149, np.float64(0.06105941257599791)),
 (150, np.float64(0.0958706236059213)),
 (151, np.float64(0.07151985398521515)),
 (152, np.float64(0.08823529411764704)),
 (153, np.float64(0.06239177481057771)),
 (154, np.float64(0.03241018617760821)),
 (155, np.float64(0.0)),
 (156, np.float64(0.0422200330920749)),
 (157, np.float64(0.0700140042014005)),
 (158, np.float64(0.11669000700233415)),
 (159, np.float64(0.06726727939963124)),
 (160, np.float64(0.07075491376772249)),
 (161, np.float64(0.03363363969981562)),
 (162, np.float64(0.0700140042014005)),
 (163, np.float64(0.026462806201248155)),
 (164, np.float64(0.08458258116519013)),
 (165, np.float64(0.024014605321403704)),
 (166, np.float64(0.05230657809659414)),
 (167, np.float64(0.1592324388246205)),
 (168, np.float64(0.10461315619318828)),
 (169, np.float64(0.11562432251572008)),
 (170, np.float64(0.06755660236665673)),
 (171, np.float64(0.12007302660701852)),
 (172, np.float64(0.07484811885651196)),
 (173, np.float64(0.04899959575500252)),
 (174, np.float64(0.08134892168199606)),
 (175, np.float64(0.05003127932742599)),
 (176, np.float64(0.06160411036336974)),
 (177, np.float64(0.0)),
 (178, np.float64(0.10341753799900383)),
 (179, np.float64(0.03834824944236852)),
 (180, np.float64(0.023338001400466827)),
 (181, np.float64(0.04802921064280741)),
 (182, np.float64(0.07349939363250378)),
 (183, np.float64(0.07397267214553091)),
 (184, np.float64(0.05230657809659414)),
 (185, np.float64(0.026462806201248155)),
 (186, np.float64(0.041594516540385144)),
 (187, np.float64(0.18981415059132412)),
 (188, np.float64(0.023338001400466827)),
 (189, np.float64(0.08084520834544433)),
 (190, np.float64(0.1562904982411873)),
 (191, np.float64(0.1292719224987548)),
 (192, np.float64(0.05003127932742599)),
 (193, np.float64(0.13263515206157422)),
 (194, np.float64(0.0)),
 (195, np.float64(0.06262242910851494)),
 (196, np.float64(0.05423261445466404)),
 (197, np.float64(0.07817631049941041)),
 (198, np.float64(0.06063390625908323)),
 (199, np.float64(0.27749837403772815)),
 (200, np.float64(0.03742405942825598)),
 (201, np.float64(0.0)),
 (202, np.float64(0.03300491809922247)),
 (203, np.float64(0.05797710356524483)),
 (204, np.float64(0.02615328904829707)),
 (205, np.float64(0.07868894753646336)),
 (206, np.float64(0.09772038812426302)),
 (207, np.float64(0.08035073760083702)),
 (208, np.float64(0.09723055853282464)),
 (209, np.float64(0.10727978097782273)),
 (210, np.float64(0.05292561240249631)),
 (211, np.float64(0.025854384499750957)),
 (212, np.float64(0.04624972900628803)),
 (213, np.float64(0.041594516540385144)),
 (214, np.float64(0.0)),
 (215, np.float64(0.09335200560186731)),
 (216, np.float64(0.20579830217101058)),
 (217, np.float64(0.06755660236665673)),
 (218, np.float64(0.040422604172722164)),
 (219, np.float64(0.06482037235521643)),
 (220, np.float64(0.09240616554505461)),
 (221, np.float64(0.05003127932742599)),
 (222, np.float64(0.10475943427376402)),
 (223, np.float64(0.05423261445466404)),
 (224, np.float64(0.02127178149057585)),
 (225, np.float64(0.04899959575500252)),
 (226, np.float64(0.06369297552984819)),
 (227, np.float64(0.11595420713048966)),
 (228, np.float64(0.06937459350943204)),
 (229, np.float64(0.0378777009539285)),
 (230, np.float64(0.03883678186903086)),
 (231, np.float64(0.0)),
 (232, np.float64(0.11595420713048966)),
 (233, np.float64(0.07151985398521515)),
 (234, np.float64(0.11357771260606365)),
 (235, np.float64(0.053567158400558014)),
 (236, np.float64(0.030316953129541614)),
 (237, np.float64(0.0700140042014005)),
 (238, np.float64(0.07767356373806172)),
 (239, np.float64(0.03834824944236852)),
 (240, np.float64(0.09901475429766743)),
 (241, np.float64(0.08346223261119858)),
 (242, np.float64(0.08458258116519013)),
 (243, np.float64(0.09799919151000504)),
 (244, np.float64(0.03241018617760821)),
 (245, np.float64(0.057166195047502935)),
 (246, np.float64(0.08028956459037002)),
 (247, np.float64(0.031846487764924096)),
 (248, np.float64(0.04711428474315455)),
 (249, np.float64(0.07151985398521515)),
 (250, np.float64(0.03363363969981562)),
 (251, np.float64(0.0)),
 (252, np.float64(0.06431196942844081)),
 (253, np.float64(0.044280744277004756)),
 (254, np.float64(0.04899959575500252)),
 (255, np.float64(0.026462806201248155)),
 (256, np.float64(0.03834824944236852)),
 (257, np.float64(0.05564148840746572)),
 (258, np.float64(0.05613608914238397)),
 (259, np.float64(0.06482037235521643)),
 (260, np.float64(0.09553946329477228)),
 (261, np.float64(0.02556549962824568)),
 (262, np.float64(0.09007546982220897)),
 (263, np.float64(0.10289915108550529)),
 (264, np.float64(0.0)),
 (265, np.float64(0.05797710356524483)),
 (266, np.float64(0.051708768999501914)),
 (267, np.float64(0.10289915108550529)),
 (268, np.float64(0.05564148840746572)),
 (269, np.float64(0.03131121455425747)),
 (270, np.float64(0.09086217008485092)),
 (271, np.float64(0.09901475429766743)),
 (272, np.float64(0.0)),
 (273, np.float64(0.0893088561378213)),
 (274, np.float64(0.04067446084099803)),
 (275, np.float64(0.029854071701326604)),
 (276, np.float64(0.1320196723968899)),
 (277, np.float64(0.03742405942825598)),
 (278, np.float64(0.04899959575500252)),
 (279, np.float64(0.04850712500726659)),
 (280, np.float64(0.05492350363810897)),
 (281, np.float64(0.04583492485141056)),
 (282, np.float64(0.04711428474315455)),
 (283, np.float64(0.028988551782622416)),
 (284, np.float64(0.03883678186903086)),
 (285, np.float64(0.06193801042615004)),
 (286, np.float64(0.08258401390153339)),
 (287, np.float64(0.027461751819054483)),
 (288, np.float64(0.0)),
 (289, np.float64(0.04850712500726659)),
 (290, np.float64(0.06600983619844494)),
 (291, np.float64(0.05230657809659414)),
 (292, np.float64(0.0939336436627724)),
 (293, np.float64(0.03131121455425747)),
 (294, np.float64(0.09095085938862485)),
 (295, np.float64(0.05564148840746572)),
 (296, np.float64(0.06149400462680908)),
 (297, np.float64(0.023338001400466827)),
 (298, np.float64(0.0)),
 (299, np.float64(0.06285566056425843)),
 (300, np.float64(0.05113099925649136)),
 (301, np.float64(0.03934447376823168)),
 (302, np.float64(0.04899959575500252)),
 (303, np.float64(0.029411764705882346)),
 (304, np.float64(0.09737260471306503)),
 (305, np.float64(0.06642111641550713)),
 (306, np.float64(0.028194193721730043)),
 (307, np.float64(0.08213292636386628)),
 (308, np.float64(0.03575992699260758)),
 (309, np.float64(0.06600983619844494)),
 (310, np.float64(0.12964074471043285)),
 (311, np.float64(0.02615328904829707)),
 (312, np.float64(0.07938841860374446)),
 (313, np.float64(0.0)),
 (314, np.float64(0.0)),
 (315, np.float64(0.11764705882352938)),
 (316, np.float64(0.020951886854752806)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.034299717028501764)),
 (320, np.float64(0.03241018617760821)),
 (321, np.float64(0.0)),
 (322, np.float64(0.08238525545716345)),
 (323, np.float64(0.03131121455425747)),
 (324, np.float64(0.02556549962824568)),
 (325, np.float64(0.140028008402801)),
 (326, np.float64(0.029854071701326604)),
 (327, np.float64(0.057166195047502935)),
 (328, np.float64(0.05797710356524483)),
 (329, np.float64(0.11128297681493143)),
 (330, np.float64(0.10585122480499262)),
 (331, np.float64(0.09513029883089881)),
 (332, np.float64(0.08458258116519013)),
 (333, np.float64(0.02556549962824568)),
 (334, np.float64(0.10114434748483471)),
 (335, np.float64(0.04850712500726659)),
 (336, np.float64(0.07312724241271305)),
 (337, np.float64(0.024014605321403704)),
 (338, np.float64(0.0)),
 (339, np.float64(0.07756315349925287)),
 (340, np.float64(0.15877683720748895)),
 (341, np.float64(0.05797710356524483)),
 (342, np.float64(0.1129464917246783)),
 (343, np.float64(0.04070627505066527)),
 (344, np.float64(0.03131121455425747)),
 (345, np.float64(0.04850712500726659)),
 (346, np.float64(0.028988551782622416)),
 (347, np.float64(0.0)),
 (348, np.float64(0.06482037235521643)),
 (349, np.float64(0.10713431680111603)),
 (350, np.float64(0.051708768999501914)),
 (351, np.float64(0.024014605321403704)),
 (352, np.float64(0.05797710356524483)),
 (353, np.float64(0.021780342093451605)),
 (354, np.float64(0.0)),
 (355, np.float64(0.05788529495093047)),
 (356, np.float64(0.06369297552984819)),
 (357, np.float64(0.0)),
 (358, np.float64(0.06262242910851494)),
 (359, np.float64(0.1320196723968899)),
 (360, np.float64(0.0)),
 (361, np.float64(0.10585122480499262)),
 (362, np.float64(0.03300491809922247)),
 (363, np.float64(0.041594516540385144)),
 (364, np.float64(0.049507377148833714)),
 (365, np.float64(0.0)),
 (366, np.float64(0.029411764705882346)),
 (367, np.float64(0.0)),
 (368, np.float64(0.06859943405700353)),
 (369, np.float64(0.08035073760083702)),
 (370, np.float64(0.053567158400558014)),
 (371, np.float64(0.05003127932742599)),
 (372, np.float64(0.05003127932742599)),
 (373, np.float64(0.0)),
 (374, np.float64(0.08028956459037002)),
 (375, np.float64(0.021437323142813602)),
 (376, np.float64(0.04899959575500252)),
 (377, np.float64(0.02449979787750126)),
 (378, np.float64(0.03241018617760821)),
 (379, np.float64(0.08939981748151894)),
 (380, np.float64(0.027461751819054483)),
 (381, np.float64(0.08856148855400951)),
 (382, np.float64(0.0)),
 (383, np.float64(0.06875238727711584)),
 (384, np.float64(0.12126781251816646)),
 (385, np.float64(0.030316953129541614)),
 (386, np.float64(0.06937459350943204)),
 (387, np.float64(0.025015639663712994)),
 (388, np.float64(0.024253562503633294)),
 (389, np.float64(0.12320822072673948)),
 (390, np.float64(0.02782074420373286)),
 (391, np.float64(0.07974522228289)),
 (392, np.float64(0.09553946329477228)),
 (393, np.float64(0.0)),
 (394, np.float64(0.02615328904829707)),
 (395, np.float64(0.0)),
 (396, np.float64(0.023124864503144014)),
 (397, np.float64(0.05492350363810897)),
 (398, np.float64(0.046676002800933654)),
 (399, np.float64(0.025015639663712994)),
 (400, np.float64(0.06262242910851494)),
 (401, np.float64(0.0)),
 (402, np.float64(0.05492350363810897)),
 (403, np.float64(0.1097907187727647)),
 (404, np.float64(0.0)),
 (405, np.float64(0.05882352941176469)),
 (406, np.float64(0.0)),
 (407, np.float64(0.06755660236665673)),
 (408, np.float64(0.034299717028501764)),
 (409, np.float64(0.049507377148833714)),
 (410, np.float64(0.05113099925649136)),
 (411, np.float64(0.08346223261119858)),
 (412, np.float64(0.150093837982278)),
 (413, np.float64(0.05882352941176469)),
 (414, np.float64(0.031846487764924096)),
 (415, np.float64(0.01871202971412799)),
 (416, np.float64(0.053567158400558014)),
 (417, np.float64(0.034299717028501764)),
 (418, np.float64(0.03742405942825598)),
 (419, np.float64(0.07204381596421111)),
 (420, np.float64(0.0942285694863091)),
 (421, np.float64(0.0)),
 (422, np.float64(0.030316953129541614)),
 (423, np.float64(0.04356068418690321)),
 (424, np.float64(0.03908815524970521)),
 (425, np.float64(0.09007546982220897)),
 (426, np.float64(0.05647324586233915)),
 (427, np.float64(0.08346223261119858)),
 (428, np.float64(0.059016710652347516)),
 (429, np.float64(0.0)),
 (430, np.float64(0.0)),
 (431, np.float64(0.05113099925649136)),
 (432, np.float64(0.04802921064280741)),
 (433, np.float64(0.03300491809922247)),
 (434, np.float64(0.025015639663712994)),
 (435, np.float64(0.07484811885651196)),
 (436, np.float64(0.02711630722733202)),
 (437, np.float64(0.05423261445466404)),
 (438, np.float64(0.0)),
 (439, np.float64(0.0)),
 (440, np.float64(0.0)),
 (441, np.float64(0.0)),
 (442, np.float64(0.023782574707724703)),
 (443, np.float64(0.06755660236665673)),
 (444, np.float64(0.024753688574416857)),
 (445, np.float64(0.02615328904829707)),
 (446, np.float64(0.02449979787750126)),
 (447, np.float64(0.04543108504242546)),
 (448, np.float64(0.045037734911104486)),
 (449, np.float64(0.028583097523751468)),
 (450, np.float64(0.022327214034455325)),
 (451, np.float64(0.026462806201248155)),
 (452, np.float64(0.03241018617760821)),
 (453, np.float64(0.025854384499750957)),
 (454, np.float64(0.04850712500726659)),
 (455, np.float64(0.042874646285627205)),
 (456, np.float64(0.02291746242570528)),
 (457, np.float64(0.12126781251816646)),
 (458, np.float64(0.04583492485141056)),
 (459, np.float64(0.03656362120635653)),
 (460, np.float64(0.05113099925649136)),
 (461, np.float64(0.08823529411764704)),
 (462, np.float64(0.034129494057038114)),
 (463, np.float64(0.0)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.07484811885651196)),
 (467, np.float64(0.06698164210336598)),
 (468, np.float64(0.05882352941176469)),
 (469, np.float64(0.08380754741901122)),
 (470, np.float64(0.04802921064280741)),
 (471, np.float64(0.09007546982220897)),
 (472, np.float64(0.11277677488692017)),
 (473, np.float64(0.046676002800933654)),
 (474, np.float64(0.0)),
 (475, np.float64(0.06937459350943204)),
 (476, np.float64(0.03500700210070025)),
 (477, np.float64(0.0)),
 (478, np.float64(0.057166195047502935)),
 (479, np.float64(0.03720326659021622)),
 (480, np.float64(0.07669649888473704)),
 (481, np.float64(0.025015639663712994)),
 (482, np.float64(0.0)),
 (483, np.float64(0.09723055853282464)),
 (484, np.float64(0.06160411036336974)),
 (485, np.float64(0.08346223261119858)),
 (486, np.float64(0.10138954626279946)),
 (487, np.float64(0.06369297552984819)),
 (488, np.float64(0.05278615073083401)),
 (489, np.float64(0.042874646285627205)),
 (490, np.float64(0.07312724241271305)),
 (491, np.float64(0.06285566056425843)),
 (492, np.float64(0.08035073760083702)),
 (493, np.float64(0.03241018617760821)),
 (494, np.float64(0.03575992699260758)),
 (495, np.float64(0.06600983619844494)),
 (496, np.float64(0.017977936632415484)),
 (497, np.float64(0.034299717028501764)),
 (498, np.float64(0.07151985398521515)),
 (499, np.float64(0.02782074420373286)),
 (500, np.float64(0.027461751819054483)),
 (501, np.float64(0.06482037235521643)),
 (502, np.float64(0.046676002800933654)),
 (503, np.float64(0.07938841860374446)),
 (504, np.float64(0.03241018617760821)),
 (505, np.float64(0.0700140042014005)),
 (506, np.float64(0.0)),
 (507, np.float64(0.06698164210336598)),

In [72]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1214, np.float64(0.29986532511593345)),
 (2405, np.float64(0.28644594961577313)),
 (507, np.float64(0.2710098294963041)),
 (539, np.float64(0.2706659809803833)),
 (1202, np.float64(0.2625754538144587))]

In [73]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [74]:
# new_df[new_df['title']=='Batman Begin'].index[0]
new_df[new_df['title']=='John Carter'].index[0]

np.int64(4)

In [75]:
def recommend(movie):
    movies_index=new_df[new_df['title']==movie].index[0]
    distance=similarity[movies_index]
    movie_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[0:8]
    
    for i in movie_list:
        print(new_df.iloc[i[0]]['title'])

In [76]:
recommend('Batman Begins')

Batman Begins
The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf
Rockaway
Batman v Superman: Dawn of Justice

In [77]:
recommend('The Dark Knight Rises')

The Dark Knight Rises
The Dark Knight
Batman Returns
Batman
Batman Forever
Batman Begins
Batman
Batman & Robin

In [78]:
new_df.iloc[1214]['title']

'Aliens vs Predator: Requiem'

In [79]:
import os
import joblib

In [80]:
# new_df and similarity are what you already have in memory
joblib.dump(new_df, 'src/trove/movie_list.pkl', compress=3)     # smaller than pickle
joblib.dump(similarity, 'src/trove/similarity.pkl', compress=3)

['src/trove/similarity.pkl']